item {
    id: 1
    name: 'name'
}

item {
    id: 2
    name: 'age'
}

item {
    id: 3
    name: 'gender'
}

item {
    id: 4
    name: 'nation'
}

item {
    id: 5
    name: 'country'
}

item {
    id: 6
    name: 'insurance_no'
}

item {
    id: 7
    name: 'address'
}

item {
    id: 8
    name: 'admission_date'
}

item {
    id: 9
    name: 'discharge_date'
}

item {
    id: 10
    name: 'diagnostic'
}

item {
    id: 11
    name: 'solution'
}

item {
    id: 12
    name: 'note'
}

item {
    id: 13
    name: 'job'
}
